# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"u\n\x07Product\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x06images\x18\x03 \x01(\x0b\x32\x17.product.Product.Images\x1a&\n\x06Images\x12\r\n\x05small\x18\x01 \x01(\t\x12\r\n\x05large\x18\x02 \x01(\t\"(\n\x18GetProductsBySkusRequest\x12\x0c\n\x04skus\x18\x01 \x03(\t\"\"\n\x12GetProductsRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"-\n\x08Products\x12!\n\x07product\x18\x01 \x03(\x0b\x32\x10.product.Product2\x9a\x01\n\x0eProductService\x12=\n\x0bGetProducts\x12\x1b.product.GetProductsRequest\x1a\x11.product.Products\x12I\n\x11GetProductsBySkus\x12!.product.GetProductsBySkusRequest\x1a\x11.product.Productsb\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_PRODUCT_IMAGES = _PRODUCT.nested_types_by_name['Images']
_GETPRODUCTSBYSKUSREQUEST = DESCRIPTOR.message_types_by_name['GetProductsBySkusRequest']
_GETPRODUCTSREQUEST = DESCRIPTOR.message_types_by_name['GetProductsRequest']
_PRODUCTS = DESCRIPTOR.message_types_by_name['Products']
Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {

  'Images' : _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
    'DESCRIPTOR' : _PRODUCT_IMAGES,
    '__module__' : 'product_pb2'
    # @@protoc_insertion_point(class_scope:product.Product.Images)
    })
  ,
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.Product)
  })
_sym_db.RegisterMessage(Product)
_sym_db.RegisterMessage(Product.Images)

GetProductsBySkusRequest = _reflection.GeneratedProtocolMessageType('GetProductsBySkusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTSBYSKUSREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetProductsBySkusRequest)
  })
_sym_db.RegisterMessage(GetProductsBySkusRequest)

GetProductsRequest = _reflection.GeneratedProtocolMessageType('GetProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTSREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetProductsRequest)
  })
_sym_db.RegisterMessage(GetProductsRequest)

Products = _reflection.GeneratedProtocolMessageType('Products', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTS,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.Products)
  })
_sym_db.RegisterMessage(Products)

_PRODUCTSERVICE = DESCRIPTOR.services_by_name['ProductService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=26
  _PRODUCT._serialized_end=143
  _PRODUCT_IMAGES._serialized_start=105
  _PRODUCT_IMAGES._serialized_end=143
  _GETPRODUCTSBYSKUSREQUEST._serialized_start=145
  _GETPRODUCTSBYSKUSREQUEST._serialized_end=185
  _GETPRODUCTSREQUEST._serialized_start=187
  _GETPRODUCTSREQUEST._serialized_end=221
  _PRODUCTS._serialized_start=223
  _PRODUCTS._serialized_end=268
  _PRODUCTSERVICE._serialized_start=271
  _PRODUCTSERVICE._serialized_end=425
# @@protoc_insertion_point(module_scope)
