# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprice.proto\x12\x07pricing\"F\n\x0cProductPrice\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x15\n\roriginalPrice\x18\x02 \x01(\x01\x12\x12\n\nfinalPrice\x18\x03 \x01(\x01\"?\n\x0eProductsPrices\x12-\n\x0eproductsPrices\x18\x01 \x03(\x0b\x32\x15.pricing.ProductPrice\"(\n\x19SingleProductPriceRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"%\n\x15ProductsPricesRequest\x12\x0c\n\x04skus\x18\x01 \x03(\t2\x96\x02\n\x13ProductPriceService\x12Q\n\x14GetProductPriceBySku\x12\".pricing.SingleProductPriceRequest\x1a\x15.pricing.ProductPrice\x12R\n\x17GetProductsPricesBySkus\x12\x1e.pricing.ProductsPricesRequest\x1a\x17.pricing.ProductsPrices\x12X\n\x1dGetProductsPricesStreamBySkus\x12\x1e.pricing.ProductsPricesRequest\x1a\x15.pricing.ProductPrice0\x01\x62\x06proto3')



_PRODUCTPRICE = DESCRIPTOR.message_types_by_name['ProductPrice']
_PRODUCTSPRICES = DESCRIPTOR.message_types_by_name['ProductsPrices']
_SINGLEPRODUCTPRICEREQUEST = DESCRIPTOR.message_types_by_name['SingleProductPriceRequest']
_PRODUCTSPRICESREQUEST = DESCRIPTOR.message_types_by_name['ProductsPricesRequest']
ProductPrice = _reflection.GeneratedProtocolMessageType('ProductPrice', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTPRICE,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:pricing.ProductPrice)
  })
_sym_db.RegisterMessage(ProductPrice)

ProductsPrices = _reflection.GeneratedProtocolMessageType('ProductsPrices', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSPRICES,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:pricing.ProductsPrices)
  })
_sym_db.RegisterMessage(ProductsPrices)

SingleProductPriceRequest = _reflection.GeneratedProtocolMessageType('SingleProductPriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEPRODUCTPRICEREQUEST,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:pricing.SingleProductPriceRequest)
  })
_sym_db.RegisterMessage(SingleProductPriceRequest)

ProductsPricesRequest = _reflection.GeneratedProtocolMessageType('ProductsPricesRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSPRICESREQUEST,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:pricing.ProductsPricesRequest)
  })
_sym_db.RegisterMessage(ProductsPricesRequest)

_PRODUCTPRICESERVICE = DESCRIPTOR.services_by_name['ProductPriceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTPRICE._serialized_start=24
  _PRODUCTPRICE._serialized_end=94
  _PRODUCTSPRICES._serialized_start=96
  _PRODUCTSPRICES._serialized_end=159
  _SINGLEPRODUCTPRICEREQUEST._serialized_start=161
  _SINGLEPRODUCTPRICEREQUEST._serialized_end=201
  _PRODUCTSPRICESREQUEST._serialized_start=203
  _PRODUCTSPRICESREQUEST._serialized_end=240
  _PRODUCTPRICESERVICE._serialized_start=243
  _PRODUCTPRICESERVICE._serialized_end=521
# @@protoc_insertion_point(module_scope)
