# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: searchProduct.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stock_pb2 as stock__pb2
import price_pb2 as price__pb2
import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13searchProduct.proto\x12\rsearchProduct\x1a\x0bstock.proto\x1a\x0bprice.proto\x1a\rproduct.proto\"\x8c\x01\n\x0f\x43ompleteProduct\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\x12\"\n\x05stock\x18\x02 \x01(\x0b\x32\x13.stock.ProductStock\x12$\n\x05price\x18\x03 \x01(\x0b\x32\x15.pricing.ProductPrice\x12\x0c\n\x04sara\x18\x05 \x01(\t\"C\n\x10\x43ompleteProducts\x12/\n\x07product\x18\x01 \x03(\x0b\x32\x1e.searchProduct.CompleteProduct\"\x1b\n\x0bTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"\x19\n\nSkuRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t2\x8a\x03\n\x14SearchProductService\x12T\n\x15GetProductsDataByTerm\x12\x1a.searchProduct.TermRequest\x1a\x1f.searchProduct.CompleteProducts\x12[\n\x1bGetProductsDataStreamByTerm\x12\x1a.searchProduct.TermRequest\x1a\x1e.searchProduct.CompleteProduct0\x01\x12[\n\x1bGetProductsDataBySkusStream\x12\x19.searchProduct.SkuRequest\x1a\x1f.searchProduct.CompleteProducts(\x01\x12\x62\n!GetProductsDataStreamBySkusStream\x12\x19.searchProduct.SkuRequest\x1a\x1e.searchProduct.CompleteProduct(\x01\x30\x01\x62\x06proto3')



_COMPLETEPRODUCT = DESCRIPTOR.message_types_by_name['CompleteProduct']
_COMPLETEPRODUCTS = DESCRIPTOR.message_types_by_name['CompleteProducts']
_TERMREQUEST = DESCRIPTOR.message_types_by_name['TermRequest']
_SKUREQUEST = DESCRIPTOR.message_types_by_name['SkuRequest']
CompleteProduct = _reflection.GeneratedProtocolMessageType('CompleteProduct', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEPRODUCT,
  '__module__' : 'searchProduct_pb2'
  # @@protoc_insertion_point(class_scope:searchProduct.CompleteProduct)
  })
_sym_db.RegisterMessage(CompleteProduct)

CompleteProducts = _reflection.GeneratedProtocolMessageType('CompleteProducts', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEPRODUCTS,
  '__module__' : 'searchProduct_pb2'
  # @@protoc_insertion_point(class_scope:searchProduct.CompleteProducts)
  })
_sym_db.RegisterMessage(CompleteProducts)

TermRequest = _reflection.GeneratedProtocolMessageType('TermRequest', (_message.Message,), {
  'DESCRIPTOR' : _TERMREQUEST,
  '__module__' : 'searchProduct_pb2'
  # @@protoc_insertion_point(class_scope:searchProduct.TermRequest)
  })
_sym_db.RegisterMessage(TermRequest)

SkuRequest = _reflection.GeneratedProtocolMessageType('SkuRequest', (_message.Message,), {
  'DESCRIPTOR' : _SKUREQUEST,
  '__module__' : 'searchProduct_pb2'
  # @@protoc_insertion_point(class_scope:searchProduct.SkuRequest)
  })
_sym_db.RegisterMessage(SkuRequest)

_SEARCHPRODUCTSERVICE = DESCRIPTOR.services_by_name['SearchProductService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPLETEPRODUCT._serialized_start=80
  _COMPLETEPRODUCT._serialized_end=220
  _COMPLETEPRODUCTS._serialized_start=222
  _COMPLETEPRODUCTS._serialized_end=289
  _TERMREQUEST._serialized_start=291
  _TERMREQUEST._serialized_end=318
  _SKUREQUEST._serialized_start=320
  _SKUREQUEST._serialized_end=345
  _SEARCHPRODUCTSERVICE._serialized_start=348
  _SEARCHPRODUCTSERVICE._serialized_end=742
# @@protoc_insertion_point(module_scope)
