# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.stock_pb2 as stock__pb2


class ProductStockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductStockBySku = channel.unary_unary(
                '/stock.ProductStockService/GetProductStockBySku',
                request_serializer=stock__pb2.SingleProductStockRequest.SerializeToString,
                response_deserializer=stock__pb2.ProductStock.FromString,
                )
        self.GetProductsStockBySkus = channel.unary_unary(
                '/stock.ProductStockService/GetProductsStockBySkus',
                request_serializer=stock__pb2.ProductsStockRequest.SerializeToString,
                response_deserializer=stock__pb2.ProductsStock.FromString,
                )


class ProductStockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductStockBySku(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductsStockBySkus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductStockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductStockBySku': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductStockBySku,
                    request_deserializer=stock__pb2.SingleProductStockRequest.FromString,
                    response_serializer=stock__pb2.ProductStock.SerializeToString,
            ),
            'GetProductsStockBySkus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsStockBySkus,
                    request_deserializer=stock__pb2.ProductsStockRequest.FromString,
                    response_serializer=stock__pb2.ProductsStock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stock.ProductStockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductStockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductStockBySku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.ProductStockService/GetProductStockBySku',
            stock__pb2.SingleProductStockRequest.SerializeToString,
            stock__pb2.ProductStock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProductsStockBySkus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.ProductStockService/GetProductsStockBySkus',
            stock__pb2.ProductsStockRequest.SerializeToString,
            stock__pb2.ProductsStock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
