# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x05stock\"-\n\x0cProductStock\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\":\n\rProductsStock\x12)\n\x0cproductStock\x18\x01 \x03(\x0b\x32\x13.stock.ProductStock\"(\n\x19SingleProductStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"$\n\x14ProductsStockRequest\x12\x0c\n\x04skus\x18\x01 \x03(\t2\xb1\x01\n\x13ProductStockService\x12M\n\x14GetProductStockBySku\x12 .stock.SingleProductStockRequest\x1a\x13.stock.ProductStock\x12K\n\x16GetProductsStockBySkus\x12\x1b.stock.ProductsStockRequest\x1a\x14.stock.ProductsStockb\x06proto3')



_PRODUCTSTOCK = DESCRIPTOR.message_types_by_name['ProductStock']
_PRODUCTSSTOCK = DESCRIPTOR.message_types_by_name['ProductsStock']
_SINGLEPRODUCTSTOCKREQUEST = DESCRIPTOR.message_types_by_name['SingleProductStockRequest']
_PRODUCTSSTOCKREQUEST = DESCRIPTOR.message_types_by_name['ProductsStockRequest']
ProductStock = _reflection.GeneratedProtocolMessageType('ProductStock', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSTOCK,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ProductStock)
  })
_sym_db.RegisterMessage(ProductStock)

ProductsStock = _reflection.GeneratedProtocolMessageType('ProductsStock', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSSTOCK,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ProductsStock)
  })
_sym_db.RegisterMessage(ProductsStock)

SingleProductStockRequest = _reflection.GeneratedProtocolMessageType('SingleProductStockRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEPRODUCTSTOCKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.SingleProductStockRequest)
  })
_sym_db.RegisterMessage(SingleProductStockRequest)

ProductsStockRequest = _reflection.GeneratedProtocolMessageType('ProductsStockRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSSTOCKREQUEST,
  '__module__' : 'stock_pb2'
  # @@protoc_insertion_point(class_scope:stock.ProductsStockRequest)
  })
_sym_db.RegisterMessage(ProductsStockRequest)

_PRODUCTSTOCKSERVICE = DESCRIPTOR.services_by_name['ProductStockService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTSTOCK._serialized_start=22
  _PRODUCTSTOCK._serialized_end=67
  _PRODUCTSSTOCK._serialized_start=69
  _PRODUCTSSTOCK._serialized_end=127
  _SINGLEPRODUCTSTOCKREQUEST._serialized_start=129
  _SINGLEPRODUCTSTOCKREQUEST._serialized_end=169
  _PRODUCTSSTOCKREQUEST._serialized_start=171
  _PRODUCTSSTOCKREQUEST._serialized_end=207
  _PRODUCTSTOCKSERVICE._serialized_start=210
  _PRODUCTSTOCKSERVICE._serialized_end=387
# @@protoc_insertion_point(module_scope)
